network:
  version 2
  ethernets:
    eth0:
      dhcp4: no
      dhcp6: no
      addresses: [+192.168.10.10//24]
      gateway4: 192.168.10.1
      nameservers:
        addresses: [192.168.10.1,8.8.8.8]